import{a as S,S as d,i as u}from"./assets/vendor-6e0bf343.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const l of e.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function r(t){if(t.ep)return;t.ep=!0;const e=a(t);fetch(t.href,e)}})();async function y(o,s){const t=`https://pixabay.com/api/?key=39588460-df52399cf23d63ffd2a80219a&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${s}&per_page=15`;try{const e=await S.get(t);return console.log(e),!e.data.hits||e.data.hits.length===0?[]:e.data}catch(e){return console.error("Error fetching images:",e),[]}}const q=new d(".gallery a",{captionDelay:250,captionsData:"alt"});function p(o){const s=document.querySelector(".gallery"),a=r(o);s.insertAdjacentHTML("beforeend",a),q.refresh();function r(t){return t.map(({webformatURL:e,largeImageURL:l,tags:b,likes:L,views:v,comments:w,downloads:$})=>`
     <li class="gallery-item">
     <a class="gallery-link" href="${l}">
      <img class="gallery-image"
      src="${e}"
      alt="${b}"
      loading="lazy"
      />
     </a>
     <ul class="image-details">
       <li class="activities"><span class="details">Likes</span> ${L}</li>
       <li class="activities"><span class="details">Views</span> ${v}</li>
       <li class="activities"><span class="details">Comments</span> ${w}</li>
       <li class="activities"><span class="details">Downloads</span> ${$}</li>
     </ul>
     </li>`).join("")}}const I=new d(".gallery a",{captionDelay:250,captionsData:"alt"});document.addEventListener("DOMContentLoaded",()=>{document.querySelector(".load-more-btn").addEventListener("click",g)});const M=document.getElementById("search-form");M.addEventListener("submit",E);const f=document.querySelector(".loader"),i=document.querySelector(".load-more-btn");i.addEventListener("click",g);let n=1,c="";const x=15;async function E(o){o.preventDefault(),m(),k();const s=document.getElementById("search-input");if(c=s.value.trim(),c!==""){n=1;try{const a=await y(c,n);n*x>=a.totalHits?(console.log("last"),i.style.display="none"):i.style.display="block",s.value="",!a||!a.hits?(u.info({title:"Information",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"red",maxWidth:"500px"}),i.style.display="none"):(p(a.hits),I.refresh())}catch(a){console.error("Error fetching images:",a)}finally{h()}}}async function g(){n+=1,m();try{const o=await y(c,n);n*15>=o.totalHits&&(i.style.display="none"),p(o.hits);const s=o.totalHits,a=document.querySelector(".gallery-item");if(a){const r=a.getBoundingClientRect().height;window.scrollBy({left:0,top:r*2,behavior:"smooth"})}o.length===0||s>0&&n>=Math.ceil(s/15)?(i.style.display="none",u.info({title:"Information",message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"red",maxWidth:"500px"})):i.style.display="block"}catch(o){alert(o.message)}finally{h()}}function m(){f.style.display="block"}function h(){f.style.display="none"}function k(){const o=document.querySelector(".gallery");o.innerHTML=""}
//# sourceMappingURL=commonHelpers.js.map
