import{a as I,S as u,i as d}from"./assets/vendor-6e0bf343.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const l of e.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function s(t){if(t.ep)return;t.ep=!0;const e=r(t);fetch(t.href,e)}})();async function y(o,a){const t=`https://pixabay.com/api/?key=39588460-df52399cf23d63ffd2a80219a&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${a}&per_page=15`;try{const e=await I.get(t);return console.log(e),!e.data.hits||e.data.hits.length===0?[]:e.data}catch(e){return console.error("Error fetching images:",e),[]}}const S=new u(".gallery a",{captionDelay:250,captionsData:"alt"});function p(o){const a=document.querySelector(".gallery"),r=s(o);a.insertAdjacentHTML("beforeend",r),S.refresh();function s(t){return t.map(({webformatURL:e,largeImageURL:l,tags:v,likes:L,views:w,comments:$,downloads:x})=>`
     <li class="gallery-item">
     <a class="gallery-link" href="${l}">
      <img class="gallery-image"
      src="${e}"
      alt="${v}"
      loading="lazy"
      />
     </a>
     <ul class="image-details">
       <li class="activities"><span class="details">Likes</span> ${L}</li>
       <li class="activities"><span class="details">Views</span> ${w}</li>
       <li class="activities"><span class="details">Comments</span> ${$}</li>
       <li class="activities"><span class="details">Downloads</span> ${x}</li>
     </ul>
     </li>`).join("")}}const q=new u(".gallery a",{captionDelay:250,captionsData:"alt"});document.addEventListener("DOMContentLoaded",()=>{document.querySelector(".load-more-btn").addEventListener("click",m)});const M=document.getElementById("search-form");M.addEventListener("submit",k);const f=document.querySelector(".loader"),n=document.querySelector(".load-more-btn");n.addEventListener("click",m);let i=1,c="";const g=15;async function k(o){o.preventDefault(),h(),E();const a=document.getElementById("search-input");if(c=a.value.trim(),c!==""){i=1;try{const r=await y(c,i);i*g>=r.totalHits?(n.style.display="none",d.info({title:"Information",message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"red",maxWidth:"500px"})):n.style.display="block",a.value="",!r||!r.hits?(d.info({title:"Information",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"red",maxWidth:"500px"}),n.style.display="none"):(p(r.hits),q.refresh())}catch(r){console.error("Error fetching images:",r)}finally{b()}}}async function m(){i+=1,h();try{const o=await y(c,i);i*g>=o.totalHits&&(n.style.display="none"),p(o.hits);const a=o.totalHits,r=document.querySelector(".gallery-item");if(r){const s=r.getBoundingClientRect().height;window.scrollBy({left:0,top:s*2,behavior:"smooth"})}o.length===0||a>0&&i>=Math.ceil(a/15)?(n.style.display="none",d.info({title:"Information",message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"red",maxWidth:"500px"})):n.style.display="block"}catch(o){alert(o.message)}finally{b()}}function h(){f.style.display="block"}function b(){f.style.display="none"}function E(){const o=document.querySelector(".gallery");o.innerHTML=""}
//# sourceMappingURL=commonHelpers.js.map
